export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";

export const FILTER_NEWS_REQUEST = "FILTER_NEWS_REQUEST";
export const FILTER_NEWS_SUCCESS = "FILTER_NEWS_SUCCESS";
export const FILTER_NEWS_FAILURE = "FILTER_NEWS_FAILURE";

